### ISSUE TITLE
No response from http://localhost:50053/ui

### ISSUE THREAD

**Issue by jmugan** [dkmfbk/knowledgestore-docker#1]
Followed the instructions and started the docker container. Everything looks fine, but going to `http://localhost:50053/ui` in my browser just says "localhost didn’t send any data.
ERR_EMPTY_RESPONSE". 

When I do `docker ps` I see
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                     NAMES
a811eb0a5051        ks                  "/usr/bin/supervisord"   2 minutes ago       Up 2 minutes        0.0.0.0:50022->22/tcp, 0.0.0.0:50051->9051/tcp, 0.0.0.0:50053->9053/tcp   ks-demo
```
So that looks fine, right? 

I don't know much about Docker, so I may be doing something stupid.

The same process works on Ubuntu, it is just the Mac where I see this.

**Comment by ticiana** [comment]
Dear @jmugan , after many attempts, I found out that KS could not initiate all the processes since Docker was using only 2G for memory. I just increased the RAM and it finally works.

Thanks my dear friend Régis!
